### PR TITLE
Friendship v1

### PR DESCRIPTION
**Pull request by Guy-Gustave**
this the pull request for the second milestone frindshipV1

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
hello @Guy-Gustave 
### You have done well so far :clap: However, there are some conflicts with some files in the project, you need to fix them and submit for another code review. Good luck.
```
Gemfile.lock
app/controllers/friendships_controller.rb
app/models/friendship.rb
app/models/user.rb
app/views/users/show.html.erb
```
- Happy coding!

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Guy-Gustave 
### You have done well so far :clap: There are still a few issues to be fixed:-
- [ ] Install the required dependencies and run the command to fix errors that might arise, [follow this guide](https://github.com/microverseinc/linters-config/tree/master/ror)
- [ ] An error occurs when one wants to see users and send a friend request, see the picture below
error path
### Make the changes and submit for another code review. Good luck!
- Happy coding!

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### You are very close, however, you need to add buttons for accepting and rejecting a friend request. Implement this feature and submit for another code review. Good luck.
- Happy coding!

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle:

Hello,

Thank you for applying the suggested changes.
However, there are still some issues that must be solved 

1. It's required, and you can read [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png), that there should be a button to invite user to friendship on users list page and on single user page. There is not such a button on the single user page in your web application.

2. Kindly write tests (unit and integration) as required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)
For **unit tests**, I suggest you use **shoulda-matcher** gem

3. It's required that Posts timeline includes posts written by logged-in user and their friends which is not what is done in your web application. Kindly make it work as required. Read it [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png)

Kindly make the suggested changes and once done, please, submit a new code review request
Thanks

Mael FOSSO

**Review by rOluochKe — APPROVED** [review]
### You finally got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
