### PR TITLE
Milestone1

### PR DESCRIPTION
**Pull request by Guy-Gustave**
pull request for the first milestone

### CODE REVIEW

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 
You have done a great job implementing the changes requested by the [previous TSE](https://github.com/Guy-Gustave/ror-social-scaffold/pull/1)! 👍 You have also done a wonderful job with your project so far! Your ERD looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] You haven't assigned any Primary Keys or Foreign Keys. Take a look at this [video](https://www.youtube.com/watch?v=-CuY5ADwn24) which was linked in the requirements to learn more about them. 
Screenshot from the requirement 👇 
Screen Shot 2020-10-02 at 1 05 47 AM

- [ ] You have added the Post_ID and User_ID to the Like table which is great, however you are missing the Like ID.


****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by Guy-Gustave** [comment]
make correction as suggested by the last reviewer

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! I commend you for putting in the effort to implement the feedback from earlier reviews. There are certain suggestions I have for you though. These are:
- [ ] Your `ERD` shows no relationship between the `Post` and the `Like` tables. Please add this relationship.
- [ ] Your diagram isn't clear enough. I am unable to tell if you have an `image_link` column for your user's table. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Let's activate linter checks for this project
- [ ] Great job on the ERD, it will very professional if you could use a drawing tool to create the ERD, instead of by hand.
## [OPTIONAL]
You could use https://www.draw.io/
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by wathigo — CHANGES_REQUESTED** [review]
### Changes Required
Great job on the ER diagram.

**REQUIRED**
* Let's make sure that the linter config files as show [here](https://github.com/microverseinc/linters-config/tree/master/ror). We don't need `.stickler.yml` file for GitHub actions to work.

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @Guy-Gustave, congratulations on fixing all the comments made by the previous TSE's :+1: 
Go ahead and merge into development :slightly_smiling_face: 

_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
