### PR TITLE
add mutuals friends

### PR DESCRIPTION
**Pull request by Guy-Gustave**
a new pull request for the third milestone.
in this branch, I have displayed friends' invitation, pending for being approved and mutual friends.

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @Guy-Gustave :lollipop: 

### Thank you for your submission :handshake: your project it's working well and not breaking at any point, I particularly like that you've added an extra feature in the users' profile where you can see their pending and  sent friendship requests I think this makes it stand out from the rest :clap: :clap: :clap: let's work on the following changes :construction: :construction_worker: 

### Behaviour (previous milestone)

* [ ] There is a button to invite a user to friendship on users list page and on single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> UsersController#show displays a `Friend Request` button if the user and the current user aren't friends already

* [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

#### Project Specific

* [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

* [ ] thanks to this, we can find user friends only by user_id in friendships table

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

> You have the right associations in your User model but to be able to use them effectively you have to add the confirmed_friend method in your Friendship model so two rows are created when a friendship is confirmed

#### Integration Test cases
> Thank you for having a good amount of Unit test cases with Rspec but let's also add feature test cases
- [ ] Please let's add test cases using Rspec + Capybara specially testing the features related to friendships

### That's, it! :raised_hands: 

### Please :pray: do the changes :technologist: and submit back for a code review when you are done :memo: 

### Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Guy-Gustave, great job on this project :+1: Congratulations on fixing the comments outlined by the previous TSE :smile: However, there are a few comments we need to address before the project can be approved, kindly check the comments below:
- Kindly enable linter checks, currently, linter check is not enabled :slightly_smiling_face: 
- Kindly address this error ` cannot load such file -- rspec/core/profiler (LoadError)` when I run the test with the following command `rspec --format documentation`
- Also kindly address the typos in the README, for example `rspec` instead of rpsec` as in the README file

Once these are fixed, kindly submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Guy-Gustave** [comment]
i checked with rspec --format documentation and now it is working perfectly, and change readme

**Comment by Guy-Gustave** [comment]
also, rubocop is working perfectly

**Review by wathigo — APPROVED** [review]
### Approved :heavy_check_mark: 
Great job implementing the suggested changes.

**You may move on.**

**Simon Wathigo**

**Pull request merged**
